# Generated by Django 2.2.2 on 2019-06-26 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 7, 8, 33, 806329, tzinfo=utc)),
        ),
    ]
